language: python
sudo: true
python:
- 3.6
services:
- docker
install:
- pip install -U codecov
script:
- sudo bash test-container.sh
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: papaemmelab
  password:
    secure: xe2TkzM94LCBTkSu+SXXXXHZtMVcVSVurHuZoH/iB+obuTj/3rcUtDkuACb0IsU4egy0PdMmXtPTaVTbnXafkqFzaPG47UuTdf5HgecIncwWCCTobe0UZP1mKIZ6efx4MTrrgMtHA8b4bSxVXKk6BkzqBNJcIilkHoXZgwYm0KSoIztaCrUvO3q2ts8TD7KcKD5jPTKEn4ACr6D07Of8F9q7Dk9ypMVeFbC+DzCEadDaoSzTnn5Bvk92FSqY8XPWrzDYSAzaVrn/VnJ2h8rwRwQOlBtH+CMt+Zuew05EtoGGO1C098kEQNHNJwcba+l7lPAcmHNiazwVXDMPhrkFSAj+O1qiq5D9FFylWVRZ/RJegs5MHTaoUc87pPQ+vuQkHzJmifiIhxnMc747fbJPwxbPeGGOLhsnHaZ2y7lSyyM5VyaSDMpv3E6pGFal6GHV9MwbvQJbunyg7dHKgC7zopO6wl+H2Ce/LJcR9fnpsIRUWFHUol6vhTSI3ikuHP/Z+egaVsUIP/6s/HuDqkcgfQh/fbrL5zy/FwAQYiZCus3gKnBTpP5enh7p7V+kydCOp/yIKHDdgndIbvnGtizlS3Pz+a6GiGSIQ9EmDnTAeYv0NaylrKtokVA44mAJFXb6cEGGoiasbQnEyT4Ul32SczB/uuIbBf2F7S9LA0msPNo=
  on:
    tags: true
    repo: papaemmelab/register_apps
    python: 3.6
    branch: master
